baseURL = 'https://griffinchow980.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
# theme = "github-style" # å·²ç§»é™¤ä¸»é¢˜

pygmentsStyle = "github"
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    style = "github"
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4
    codeFences = true
    guessSyntax = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Griffin Chow"
  description = "My Hugo Blog"
  github = "griffinchow980"
  email = "griffinchow980@gmail.com"
  url = "https://griffinchow980.github.io/"
  keywords = "blog, hugo, programming"
  # rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avater_xiaomai_01.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "Earth"
  userStatusEmoji = "ğŸ˜†"
  enableGitalk = false
  enableSearch = true
  katex = true
  # å®Œæ•´çš„æ ·å¼æ–‡ä»¶é…ç½®
  custom_css = [
    "/css/frameworks.min.css",
    "/css/github.min.css", 
    "/css/github-style.css",
    "/css/light.css",
    "/css/dark.css",
    # "/css/syntax.css",
    "/css/custom-syntax.css", 
    "/css/back-to-top.css", 
    "/css/tabs.css", 
    "/css/details.css", 
    "/css/underline-nav-fix.css",
    "/css/toc.css",
    "/css/mobile-font-scale.css",
    "/css/interviews.css"
  ]
  # å®Œæ•´çš„è„šæœ¬æ–‡ä»¶é…ç½®
  custom_js = [
    "/js/theme-mode.js",
    "/js/copy-code.js", 
    "/js/back-to-top.js", 
    "/js/tabs.js", 
    # "/js/details-sort.js",
    "/js/toc.js",
    "/js/interviews.js"
  ]

  [[params.links]]
    title = "csdn"
    href = "https://meik2333.com"
    icon = "/images/csdn.png"



[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]